// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYgNxQ0rnX1LwnCC17wtmPZCQ-dRSvxNg',
    appId: '1:41943363712:web:46e766e8349d9f970c3665',
    messagingSenderId: '41943363712',
    projectId: 'final-ficr',
    authDomain: 'final-ficr.firebaseapp.com',
    storageBucket: 'final-ficr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnSYrwzS1LoDUpT-nRkD9AeKrHDbiMdfE',
    appId: '1:41943363712:android:75b4751412c1941e0c3665',
    messagingSenderId: '41943363712',
    projectId: 'final-ficr',
    storageBucket: 'final-ficr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUCJZPhDKUj8mhHTn0TBi1dlMTA0Dt1IM',
    appId: '1:41943363712:ios:e6babb3d2a7ae4790c3665',
    messagingSenderId: '41943363712',
    projectId: 'final-ficr',
    storageBucket: 'final-ficr.appspot.com',
    iosBundleId: 'com.example.finalFicr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUCJZPhDKUj8mhHTn0TBi1dlMTA0Dt1IM',
    appId: '1:41943363712:ios:e6babb3d2a7ae4790c3665',
    messagingSenderId: '41943363712',
    projectId: 'final-ficr',
    storageBucket: 'final-ficr.appspot.com',
    iosBundleId: 'com.example.finalFicr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYgNxQ0rnX1LwnCC17wtmPZCQ-dRSvxNg',
    appId: '1:41943363712:web:a3476bf886c8c70a0c3665',
    messagingSenderId: '41943363712',
    projectId: 'final-ficr',
    authDomain: 'final-ficr.firebaseapp.com',
    storageBucket: 'final-ficr.appspot.com',
  );

}